use_frameworks!

target 'AdAdaptive_Example' do
  pod 'AdAdaptive', :path => '../'

  target 'AdAdaptive_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
