use_frameworks!

target 'AdAdaptive_Example' do
  platform :ios, "10.0"
  pod 'AdAdaptive', :path => '../'

  target 'AdAdaptive_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  pod 'Alamofire', '~> 4.3'
  pod 'AlamofireImage', '~> 3.1'
  end
end
